<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    @page { margin: 2.2cm 1.6cm 2cm; }
    * { box-sizing: border-box; }
    body { font-family: DejaVu Sans, sans-serif; font-size: 10.5pt; color: #1a1d27; line-height: 1.5; }

    .doc-header { border-bottom: 2px solid #6366f1; padding-bottom: 10px; margin-bottom: 22px; }
    .doc-title { font-size: 16pt; font-weight: bold; color: #1a1d27; margin: 0 0 4px; }
    .doc-meta { font-size: 8.5pt; color: #6b7280; }

    .msg { margin-bottom: 16px; page-break-inside: avoid; }
    .msg-label { font-size: 8.5pt; font-weight: bold; margin-bottom: 3px; }
    .msg-label.user { color: #1a56db; }
    .msg-label.assistant { color: #4f46e5; }
    .msg-time { font-weight: normal; color: #9ca3af; margin-left: 6px; }

    .msg-body { border-radius: 6px; padding: 8px 12px; }
    .msg-body.user { background: #eef2ff; }
    .msg-body.assistant { background: #f7f7fb; }

    .msg-body p { margin: 0 0 6px; }
    .msg-body p:last-child { margin-bottom: 0; }
    .msg-body h1, .msg-body h2, .msg-body h3 { font-size: 11.5pt; margin: 8px 0 4px; }
    .msg-body ul, .msg-body ol { margin: 4px 0 6px 18px; padding: 0; }
    .msg-body li { margin-bottom: 2px; }
    .msg-body code { font-family: DejaVu Sans Mono, monospace; font-size: 9pt; background: rgba(0,0,0,.06); padding: 1px 4px; border-radius: 3px; }
    .msg-body pre { font-family: DejaVu Sans Mono, monospace; font-size: 8.5pt; background: #1e2433; color: #e2e8f0; padding: 8px 10px; border-radius: 6px; overflow-wrap: break-word; white-space: pre-wrap; margin: 6px 0; }
    .msg-body pre code { background: none; padding: 0; color: inherit; }

    .doc-footer { position: fixed; bottom: -1.4cm; left: 0; right: 0; font-size: 7.5pt; color: #9ca3af; text-align: center; }
</style>
</head>
<body>
    <div class="doc-header">
        <p class="doc-title">{{ $title }}</p>
        <p class="doc-meta">Exported {{ $exportedAt }} &middot; {{ count($messages) }} messages &middot; laraveleasyai</p>
    </div>

    @foreach($messages as $msg)
        <div class="msg">
            <div class="msg-label {{ $msg->role }}">
                {{ $msg->role === 'user' ? 'You' : 'Assistant' }}
                <span class="msg-time">{{ optional($msg->created_at)->format('Y-m-d H:i') }}</span>
            </div>
            <div class="msg-body {{ $msg->role }}">
                {!! \EasyAI\LaravelAI\Chat\Support\PdfMarkdown::toHtml($msg->content) !!}
            </div>
        </div>
    @endforeach

    <div class="doc-footer">Generated by LaravelAI — this conversation is exported from your own database, no external service involved.</div>
</body>
</html>
